### ISSUE TITLE
encoder and mp4 upload

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1034]
i uploaded encoder version 1 but it also needs ffmpeg and exiftool and my hosting dosent support it
and i am not able to upload mp4 file 
![opera snapshot_2018-08-23_193829_eduvid in](https://user-images.githubusercontent.com/39002772/45061867-f3313600-b0c3-11e8-8d38-57776ae857a4.png)

**Comment by Edtigoza** [comment]
you can use the free service from youphptube
this site     [https://encoder.youphptube.com/](https://encoder.youphptube.com/)
Create a user and give permission to upload videos.
login with that user and password in the free service,
I suggest, If your hosting does not support the requirements, change to one that supports it,
because if there is an update, it may take a long time
