### ISSUE TITLE
What is stream video?

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube#1071]
What does "stream video" mean in YouPHPTube? Do I need Nginx? But I installed the server on apache2. So can I use the stream video feature then?
Thanks!

**Comment by ChrisSlS** [comment]
Look this : https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server
Nginx is required for livestream fonctionnality.

**Comment by DanielnetoDotCom** [comment]
You will need to install both, Apache and Nginx

**Comment by VictorLi0213** [comment]
So do I need to install them on the same server or do I need two separate servers, one with apache and one with nginx?

**Comment by DanielnetoDotCom** [comment]
Same server, just follow @ChrisSlS post

**Comment by VictorLi0213** [comment]
Ok thanks

**Comment by VictorLi0213** [comment]
@ChrisSlS So do I just follow the instructions in that article on my server, in which apache2 is already running?

**Comment by VictorLi0213** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Just paid attention on it ...

Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16+ without any kind of control panel. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.
