### ISSUE TITLE
Problem with Youtube-dl

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube#1084]
Hi, I have installed the youtube-dl as mentioned in the website, but I still get this error:
<img width="569" alt="2018-09-16 1 06 45" src="https://user-images.githubusercontent.com/29973121/45599452-7a7a8580-b9b1-11e8-9d14-6bb243009c91.png">
What should I do?

**Comment by nightstryke** [comment]
@VictorLi0213 If you followed the directions it should work, make sure you have correctly followed the install instructions of YouPHPTube.

**Comment by nightstryke** [comment]
> Ok thank you I will try that again.
> Moreover, can you help me solve this problem:
> [DanielnetoDotCom/YouPHPTube-Encoder#91](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/issues/91)
> Thanks!
> @nightstryke

With that, I'm not sure, I would recommend trying to YouPHPTube with Apache as the webserver and nginx as the RTMP server only and seeing if that fixes your problem. You also may not have all the php modules installed which is why I said make sure you follow the install instructions to the letter here: [https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer)
