### ISSUE TITLE
virtualbox image?

### ISSUE THREAD

**Issue by slthomason** [DanielnetoDotCom/YouPHPTube#1086]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/VirtualBox-YouPHPTube-Ready

The download link doesn't work and I really wanted to try this.  Any idea how I can get a hold of this?

**Comment by DanielnetoDotCom** [comment]
I updated the download URL to https://youphptube.com/YouPHPTube_VirtualBox_Ubuntu18.zip

**Comment by weesnaw1** [comment]
Will this work for VMware?

Virtual box never works properly for me

**Comment by nightstryke** [comment]
> Will this work for VMware?
> 
> Virtual box never works properly for me

Most likely you'll have to install the image into virtualbox first and then export it to vmware. I've never had a problem with virtual box, if you're having issues with virtualization not working you may have to turn the setting on in you motherboard's bios. That usually fixes some virtualbox issues.

**Comment by MayaV369** [comment]
Hi,

As per your instruction I opened with virtual box and trying to configure the network interface, the keyboard setting in the vm image is having issue,
And then second thing is I tried to run this VM image in local IP within my school for teaching videos so i decided to change the ip address according to my school http://171.16.22.22 but with VIrtual box Network config as Bridge setting instead of NAT , it also failed and not working Im not able to access the vm image via ssh and also browser.
Third and final thing is how to i change the IP address (Local IP - Intranet IP) and run without any issue kindly help me to sort this.
Thanks

**Comment by nightstryke** [comment]
I've run it using Bridged instead of NAT so it does work.
If you use bridged then you need to setup the network according to your network. And since it's Ubuntu 18.04 you may want to try this tutorial first and then try again. [https://linuxconfig.org/how-to-configure-static-ip-address-on-ubuntu-18-04-bionic-beaver-linux](https://linuxconfig.org/how-to-configure-static-ip-address-on-ubuntu-18-04-bionic-beaver-linux)

**Comment by MayaV369** [comment]
Okay this is really helpful 

After this can i do this step ? mentioned in https://github.com/DanielnetoDotCom/YouPHPTube/wiki/VirtualBox-YouPHPTube-Ready

```
To change the current configuration IP to the new one you will need to go to the terminal and go to the directory …

cd /var/www/html/YouPHPTube/install then type sudo php updateStreamerURL.php

you will be requested to enter with your new streamer address ie: http://192.168.1.20

press enter and that is it

```

Any idea about the keyboard issue in cli ?

**Comment by DanielnetoDotCom** [comment]
After you configure your VM, try to update streamer and encoder with the latest version

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

there is no reason to not upload a 5MB file, check the log file if there is some clue

**Comment by carekapt** [comment]
Hi there.
I downloaded the virtualbox vm but I don't know the server access credentials ....any hint?

**Comment by DanielnetoDotCom** [comment]
Try root pass 123
