### ISSUE TITLE
Error when i try to install

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#119]
Hello, im trying to install but i get this error
![tttt](https://user-images.githubusercontent.com/32053243/30530218-2960cc98-9c45-11e7-908f-61c0ed145a32.png)

**Comment by Andiweb87** [comment]
SELECT * FROM categories WHERE 1=1 \nError : ()

**Comment by laweschan** [comment]
are you using default database youPHPTube or using other database naming ?

**Comment by Andiweb87** [comment]
i have removed the naming database and try to use default, the installation was succesfully but show this now and update of system

**Comment by laweschan** [comment]
try removed the naming database again, edit ./install database.sql and comment the line 
like this 

-- CREATE SCHEMA IF NOT EXISTS `youPHPTube` DEFAULT CHARACTER SET utf8 ;
-- USE `youPHPTube` ;

**Comment by Andiweb87** [comment]
not working i will try to re-install again but what is best to do put a naming database or leave it default >???

**Comment by laweschan** [comment]
no here is a bug and I already post to git, but seems developer still not commit
if you comment what I do, you can naming database as normal, but it need you manual create database with utf-8 before install

**Comment by laweschan** [comment]
what I do before,
i. drop database 
ii. comment the 2 line in database.sql
iii. recreate database with utf-8 support
iv. add user with grant database right (or you can just use mysql_root account for testing first)
v. go to UI install but select create tables only, of coz you need input the correct value in the remain field

after doing the step, I have pass the error the same as your post

**Comment by DanielnetoDotCom** [comment]
Very sorry for that, I found the issue, A missing line on database.sql installation

remove the lines:
```
-- -----------------------------------------------------
-- Schema youPHPTube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youPHPTube` DEFAULT CHARACTER SET utf8 ;
USE `youPHPTube` ;
```

or update your code with the repository.

those lines create an issue if you use a different name for the database

**Comment by Andiweb87** [comment]
Daniel thank you , show this now , and same error when i put my database names

Sorry!

Connect Error (1045) Access denied for user 'root'@'localhost' (using password: YES)

**Comment by Andiweb87** [comment]
Sorry!

Error deleting user: No database selected

**Comment by Andiweb87** [comment]
ok , fixed you can close this, just a last thing , is possible to stream with this script ??

thank you

**Comment by Andiweb87** [comment]
INSERT INTO live_transmitions ( `` ) VALUES () Error : (1146) Table 'albsport_video.live_transmitions' doesn't exist

**Comment by DanielnetoDotCom** [comment]
It is possible, but I just release it to test.
to get rid of this error you need to install the Live plugin database

![image](https://user-images.githubusercontent.com/18009293/30546917-58e5178e-9c64-11e7-953d-d2cd0fdd6e5e.png)

you also need to set up some variables , but I am still doing the documentation

**Comment by Andiweb87** [comment]
Daniel another thing can you please test with mobile if the videos i have uploaded working ?

www.albsports.com/video

**Comment by Andiweb87** [comment]
also if possible to change the dimensions of the main video in the front page ? thank you

**Comment by Andiweb87** [comment]
ok testing this site found when i upload an thumbnail for the video in mobile version the video is not open , the videois ok only when im not upload the thumbnail

**Comment by Andiweb87** [comment]
????

**Comment by DanielnetoDotCom** [comment]
Hi, usually we use the mobile version only to display videos.
To upload videos the best way is using your computer.
If you are not using the [encoder](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder), you will need to upload a thumbs for each video. otherwise your video will display an static image

**Comment by Andiweb87** [comment]
Yes i mean to see videos with mobile show only the static image only with phone, also now i have a problem with the secure site check please https://albsports.com/video/

**Comment by DanielnetoDotCom** [comment]
Maybe fixing the security issue you will fix everything.
Go to the videos/configurations.php file and change the http://albsports.com/video/ to http**s**://albsports.com/video/
I may fix the security issue

**Comment by Andiweb87** [comment]
yes , worked but still i have an connection not secure , anyway how can i talk more fast with you because I plan to develop a project on your script, do you have any fb or email adress ?

thank you

Andi

**Comment by DanielnetoDotCom** [comment]
BTW, I just test your site on Android Chrome browser and it works fine

**Comment by laweschan** [comment]
thumb is necessary to change the front view of video, this is not an issue,
or you can place a suggestion to change it. but all is respect to developer
please make your test and query much better
currently document is lack of info but I don't think it is youphptube
issue, as I also tuning apache myself to make it better for control

On Sep 19, 2017 10:28 PM, "YouPHPTube" <notifications@github.com> wrote:

Maybe fixing the security issue you will fix everything.
Go to the videos/configurations.php file and change the
http://albsports.com/video/ to http*s*://albsports.com/video/
I may fix the security issue

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/119#issuecomment-330557687>,
or mute the thread

**Comment by DanielnetoDotCom** [comment]
my email: developer@youphptube.com

**Comment by Andiweb87** [comment]
when i put the thumbnail in a video, with phone the video not start only with the generated thumbnail works

**Comment by laweschan** [comment]
can you test it clearly ?
ok, i drill a test from my Samsung phone and show the result to u

pls,  youtube.aveally.com
pls,  ensure you have go through the correct step first
I too lazy,  just upload 2 videos and change the first one with upload thumb

**Comment by Andiweb87** [comment]
the first video with thumbnail is not open the second video yes , same problem i have when i use the thumbnail and when not.

i use iphone 5s

**Comment by laweschan** [comment]
strange,  I can open 2 videos, do you have other phone for testing?
I don't have iPhone sorry

**Comment by Andiweb87** [comment]
i have tested with android phone and works with thumbnail and no thumbnail, now i think is the phone (iphone5s)  or the opera browser i use in the iphone....

**Comment by laweschan** [comment]
may be you can start discussion with developer with the email, here is not
a good place for discussion , unless confirm any bug or enhancement

cheers
On Sep 19, 2017 11:10 PM, "Andiweb87" <notifications@github.com> wrote:

i have tested with android phone and works with thumbnail and no thumbnail,
now i think is the phone (iphone5s) or the opera browser i use in the
iphone....

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/119#issuecomment-330571411>,
or mute the thread

**Comment by Andiweb87** [comment]
ok , thank you

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
