### ISSUE TITLE
Video advertising does not work

### ISSUE THREAD

**Issue by kiaraxx** [DanielnetoDotCom/YouPHPTube#1218]
the server time is set correctly.

Add the campaign, and the video to the campaign and even then it does not work.

Activate the video plugin that is not activated and does not work either.

erase cache and history and it does not work either.

Provide all the themes of the players either.

help please.

I leave photos.

https://ibb.co/m5OLuf
https://ibb.co/bQ8W0L
https://ibb.co/fN66Zf
https://ibb.co/eDRjLL

Use:
Centos 7
Plesk Panel
PHP 7.2.

URL: https://driveid.cloud

**Comment by kiaraxx** [comment]
Use centos 7 plesk panel

**Comment by DanielnetoDotCom** [comment]
make sure the ads start time is lower than the server time (NOT your PC time)

also check for Javascript errors

**Comment by kiaraxx** [comment]
@DanielnettoDotCom

could you give me an example.

could you give me an example of how you have it configured on your server.

Please.

**Comment by kiaraxx** [comment]
I leave photos

ttps://ibb.co/eHOGjf

**Comment by DanielnetoDotCom** [comment]
@karen20ced4  I can not see anything wrong with your configuration

@kiaraxx you can see my ads working on the demo site.

how did you upload the video you are using as an ad?
encoder or direct upload?

**Comment by kiaraxx** [comment]
I uploaded the video by the public encoder.
could you give an example of server time.

**Comment by DanielnetoDotCom** [comment]
@kiaraxx you need to access your server and check the server date.
just to make sure you configure it right

**Comment by karen20ced4** [comment]
Loading failed for the <script> with source “https://s0.2mdn.net/instream/video/client.js”. 2:1:1

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mysite.com/plugin/AD_Server/VMAP.php?video_length=1073&vmap_id=hn1l407bifenoov0f7pfgf82i4. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).[Learn More]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mysite.com/plugin/AD_Server/VMAP.php?video_length=1073&vmap_id=hn1l407bifenoov0f7pfgf82i4. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).[Learn More]

AdsLoader error: AdError 1012: Unable to request ads from server due to network error.

**Comment by DanielnetoDotCom** [comment]
What webserver are you using? Apache or nigix.

You probably have a cors rule somewhere blocking the adserver

**Comment by karen20ced4** [comment]
i have apache2

**Comment by DanielnetoDotCom** [comment]
As I told you, you may have a CORS rule blocking content somewhere in your server

**Comment by karen20ced4** [comment]
i comment line 36 in .htacces , and now is working for me, the ads are displayed
35:< ifModule mod_headers.c >
36:<#    Header set Access-Control-Allow-Origin: *>

**Comment by DanielnetoDotCom** [comment]
I see, thanks

Good to know it may cause ads problem
