### ISSUE TITLE
Protect videos from downloaders (ex. Jdownloader...)

### ISSUE THREAD

**Issue by RapFan89** [DanielnetoDotCom/YouPHPTube#1237]
Hi,
as the title said, i would like to know if there is a way to "lock" video download for the smarty users that uses downloader software to grab our videos.

I can already say you that i do not have any kind of root access, so every sort of modification in the system folders (etc...) is not possible to me.

Thank you so much for any answer.

**Comment by Puyodead1** [comment]
Good question, i have the SecureVideosDirectory plugin but chrome extensions (Allow right click) can still download and just save-as

**Comment by tgd1973** [comment]
Hi! Only a player built around DRM (Digital Rights Management) can guarantee data protection ... because even if you download a movie, this can not be reproduced due to the lack of a certificate that guarantees the decoding of the movie itself ...

In our case, the player with which this platform is made is VideoJS for which the DRM rights are managed with a plug  [https://github.com/videojs/videojs-contrib-eme](url)  ... which however needs to be adapted to this platform.

It remains only the will of the author, to be able to do this work.

**Comment by DanielnetoDotCom** [comment]
This is good to know, I will take a look. thanks

**Comment by RapFan89** [comment]
Hi,
there are any new about that?

**Comment by DanielnetoDotCom** [comment]
@RapFan89 , 

I am just experimenting with the new HLS encoding, what encrypt the videos.

all videos on the demo site are now HLS, can you please try to download one of them?

if you can download can you please try to encrypt?

I guess they are all protected now.
