### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by jeanfrancoisvarin** [DanielnetoDotCom/YouPHPTube#1280]
I've just updated my server and encoder following the "git pull" procedure (which I do once per week).

I proceed a reboot and now, when I try to connect, regardless of the user, I've got a wrong user or password message.

Is there a sql script to apply to the db ?

How can I solve this issue ?

Merci par avance.
JF

**Comment by DanielnetoDotCom** [comment]
we have no recent DB updates, please try to update with the latest.
we fix several issues, include fixes were released today

update your streamer and encoder

**Comment by Puyodead1** [comment]
This is related to the issue i just made, the way the passwords are stored is by Hashing them to make them secure and not plain text before they are put into the database, but the problem is the site is looking for the actual hash as the password instead of what it should be "apple" for example #1282
