### ISSUE TITLE
OBS Could not access channel

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1386]
![image](https://user-images.githubusercontent.com/14828766/51091804-96bee100-175d-11e9-84db-ef4329d2bba2.png)

**Comment by Puyodead1** [comment]
Ok, so i found the issue. My YouPHPTube site runs on https (https://puyodead1-development.me) but i also run other services on http (http://puyodead1-development.me). it appears that i need http redirecting to https to use live streaming.

**Comment by bersuit72** [comment]
hello good afternoon people, I can not make a transmission through OBS since it does not connect to the server ... what can it be? Do you have to open a port? Do you have to configure something else? It is not on my dedicated or local server


![Sin título](https://user-images.githubusercontent.com/31553331/62642849-f9a3df80-b91c-11e9-9f63-78e9329a0ac5.png)
![Sin título2](https://user-images.githubusercontent.com/31553331/62642851-fa3c7600-b91c-11e9-9941-a5b731c1804a.png)
![Sin título3](https://user-images.githubusercontent.com/31553331/62642853-fa3c7600-b91c-11e9-917f-c9bf427dff29.png)

**Comment by DanielnetoDotCom** [comment]
Looks like it could not reach your nginx server. make sure it is running.

if it is running, check your nginx log file.
