### ISSUE TITLE
quality of the videos

### ISSUE THREAD

**Issue by winklov** [DanielnetoDotCom/YouPHPTube#140]
Where can one change the quality of the videos? 
or can this be added, enable or do i need to add it to the script
144p
240p
360p
480p
720p
1080p

**Comment by DanielnetoDotCom** [comment]
The [encoder](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder) is responsible to define the resolution

![image](https://user-images.githubusercontent.com/18009293/31194939-076eb1cc-a91f-11e7-9514-62d80a71033d.png)

The Player site play only the resolution defined on the encoder

**Comment by diroots** [comment]
Hi
I think winklov asked how to propose multiple quality for a video. but configuration only permit to create one mp4 and one webm. 
how could we add some more configurations in the encoder, for it to create multiple versions of a video e.g. one of each of these : 

144p
240p
360p
480p
720p
1080p

(assuming we are giving a 1080p as a source to be able to create all the smaller versions. )

I believe there are changes to do on the encoder side, but also on the player site, for the player to be able to propose a quality switch on its bar for people to choose between quality. 

I've seen you use videojs, 
for videojs, there are 2 plugins that can be used for this purpose : 

https://www.npmjs.com/package/videojs-contrib-quality-levels
or maybe 
https://www.npmjs.com/package/videojs-contrib-hls 

for the hls part, as you are using nginx for the live part of youphptube, maybe you know that nginx can handle multibitrate hls streaming from mp4 sources, so it can be some starting point 

best

**Comment by DanielnetoDotCom** [comment]
Thanks for all those information.
This will be implemented in the future for sure. I just can't do it now. busy with some other priorities :)
But help will be welcome

**Comment by diroots** [comment]
Hello There. 

I've seen you are using video.js 5 for youphptube. 
are you plannin to soon update to videojs6 or not for the moment? 

Asking this because I found 2 other quality switcher plugins, but one is for videojs5 and one for videojs6 : 

https://github.com/kmoskwiak/videojs-resolution-switcher
and
https://github.com/silvermine/videojs-quality-selector

before trying to add this on  youphptube, I would prefer to know on which version I try some,...

**Comment by DanielnetoDotCom** [comment]
I always like to update, but before decide I need to make some tests.
Also check plugins compatibility is need before update

**Comment by winklov** [comment]
hi im using 4.1

**Comment by DanielnetoDotCom** [comment]
@winklov try this to update your files https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by DanielnetoDotCom** [comment]
BTW, now the encoder can encode 3 resolutions, Low SD and HD, the resolutions are defined on the ffmpeg code

![image](https://user-images.githubusercontent.com/18009293/32010172-75f16270-b987-11e7-8dd6-170abc75a9c1.png)

But to switch resolutions you will need a plugin available on [EasyTube.Club](https://easytube.club/signUp)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by macfori** [comment]
I would like to reopen this issue because the topic is actually important:
Up to date the HLS renderer put 7 levels of size in the multi stream file.
But the system doesn't offer a setting-panel to configure the settings for each size.
P.E. size 2048p, 1024p: I would give the renderer the chance to render with higher bitrate / videoquality an 60 fps.
But I couldn't find a place to set that up. Can I do this in the application code itself?

**Comment by DanielnetoDotCom** [comment]
If you check here 

https://github.com/WWBN/AVideo-Encoder/blob/156f42d014b6187ec4e2a1ce337887407ba94e89/objects/Format.php#L389-L401

From 540p and higher, we do not change the fps

also, you can encode up to 4k 2160p
