### ISSUE TITLE
Clone: Server Unknow ERROR.

### ISSUE THREAD

**Issue by hdavy2002** [DanielnetoDotCom/YouPHPTube#1494]
Followed tutorial and setup another machine to clone. I get an Clone: Server Unknow ERROR. Nothing i DB too. I deleted tables on Server and client and then re-installed tables. Nothing pops up in server manager too.

See screen shots. Nothing logged in /apache2/error.log and /video/youphptube.log

![annotation 2019-02-18 112734](https://user-images.githubusercontent.com/1983384/52935996-f32aa700-3380-11e9-9c1b-2d9d1ef8029d.jpg)
![annotation 2019-02-18 132430](https://user-images.githubusercontent.com/1983384/52935997-f32aa700-3380-11e9-8500-93d74a142699.jpg)
![annotation 2019-02-18 132538](https://user-images.githubusercontent.com/1983384/52935998-f3c33d80-3380-11e9-9ae0-fad1cb0e6a59.jpg)
![annotation 2019-02-18 132852](https://user-images.githubusercontent.com/1983384/52936070-22d9af00-3381-11e9-9e68-c8998ee5521b.jpg)

**Comment by DanielnetoDotCom** [comment]
you will need to check both log files, the master and the slave site.

check the YouPHPTube log file, I could not find any clue on the log file you post there

**Comment by JoshWho** [comment]
Looks like the server is timing out from PHP max script time mabe? I'm just guessing but it seems to be looking like it is cutting off the data in the middle of the transfer and causing the PHP syntax error because the files, scripts, and databases are not complete. Not sure which server is giving u that problem you didn;t really provide to much info here.
