### ISSUE TITLE
Video already watched shows only the end and stops

### ISSUE THREAD

**Issue by dfreddie** [DanielnetoDotCom/YouPHPTube#1555]
YouPHPtube ver. 6.9 but as far as I know same problem with ver. 6.6

**Comment by DanielnetoDotCom** [comment]
I see, can you reproduce it on demo site?

if you can, please let me know what video is, I will make some tests

**Comment by dfreddie** [comment]
I've tried ... no problem with demo site. Should I have to reinstall mine?

**Comment by DanielnetoDotCom** [comment]
is hard to fix something when I can not reproduce the error.

make sure you replace all your files with the master branch on GitHub

if does not work, reinstall it.

**Comment by dfreddie** [comment]
I've noticed that is produced only for logged in user.

**Comment by DanielnetoDotCom** [comment]
But I need to be able to reproduce it to be able to fix it.

**Comment by dfreddie** [comment]
There is a way to reset configuration to default?

**Comment by DanielnetoDotCom** [comment]
if you talk about plugins you can remove all json text and save it.

it will be reset to default.

![image](https://user-images.githubusercontent.com/18009293/53956407-4a878180-40ba-11e9-80e2-41678071d0b2.png)

**Comment by tgd1973** [comment]
I also join me to this problem  ...  I think the other user it refers to the fact that YouPhPTube for the logged users , memorizes the point in which it breaks, the view (you go on another page before the video ends) ... to be able to resume at a later time ... If you leave the video almost at the end ... when you return and if the autoplay is active you can not even review that video because as soon as you enter to that video you are forward on the next video proposed by autoplay ... need  with speed, immediately point videos on the bar  of time at a lower time ... to see ... something that not everyone knows how to do it ...
For this reason I prefer to look with the browser in unknown mode or logged out  ... for, not store the 
 times of the player in the sesion  ...

Perhaps, the only way to solve the problem would be to filter on the play timeline. When you arrive almost at the end of the video if by chance you go away then you go back to that video ... to re-propose, a bit back to have time to set the player for another time ...

**Comment by DanielnetoDotCom** [comment]
Hi @tgd1973  I fix this problem on the last update, can you please check it?

**Comment by tgd1973** [comment]
I loaded the fix and everything seems ok.
Thanks again.

**Comment by dfreddie** [comment]
Ok to me too. 
But can you make as an option to remember it when video is reloaded?
With this update encoder freeze at "Processing ..." when trying encode from YT.

**Comment by DanielnetoDotCom** [comment]
Make sure your streamer and encoder are up to date

**Comment by dfreddie** [comment]
There are for sure.

**Comment by DanielnetoDotCom** [comment]
check your log file for some clue
