### ISSUE TITLE
Support subtitle

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DanielnetoDotCom/YouPHPTube#16]
The support of subtitle can be a great feature.

**Comment by DanielnetoDotCom** [comment]
We can take a look on that :)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by hersche** [comment]
i would be interessted to help resolving this, but i'm still not very much in your project (should invest more intensive time there).

well, as i saw, you are using videojs?

there's this:
https://github.com/videojs/video.js/issues/1956

they say, to make it short, that the support for srt-files was there, but is gone since v4.12. anyway, they now support http://www.webvtt.org/ , where's also a converter for srt's. seems to be new kind of subtitle-default for web? would be nice!

the other site is as always db.

id(int) | lang(int/string=langid/langname) | videoid (int) | filename (string) | maybe comment, starttime, ...?

then gui, another upload-field or so in mvideos (on concrete video) and a select-list in view/include/videos.php including none as static and rest as existing for this video. default would may be the best in the user-set language when avaible. or would a checkbox to enable/disable sub's more usefull instead of the none-value?

about srt's or webvtt, i have not really a clue, but i could do other stuff, what would help you most? backend, frontend, videojs?

btw, the video which give me the motivation is this:
https://www.youtube.com/watch?v=XMm0HsmOTFI ;)

best regards

vinz

**Comment by DanielnetoDotCom** [comment]
Thanks @hersche I am thinking to use webvtt.
But it is for the future. I am engaged in something else now.
Thanks for your help I always appreciate that

**Comment by hersche** [comment]
you could let it closed, but this is the right doc our needs..

http://docs.videojs.com/docs/guides/text-tracks.html

this would be very usefull as native function (not a plugin), what do you think?

**Comment by hersche** [comment]
i've began targeting this.
it is just a backend-begin, but there are various solutions where to place a delete/add-method for example - i've created a new subtitle-class, what would may be a good place.

then, what upload-pattern should be used? videos/subtitles or subtitles direct at youphptube-root-dir?

you also add a kind of hash to videos, i assume that would be nice to stay with on uploaded files?
can you explain or refer on this point?

my little commit: https://github.com/hersche/YouPHPTube/commit/4d3f6dc9f540c24a8eacbdd72039fb2b9c5f31a3

**Comment by loso20p** [comment]
so do this support subtitle upload using the SubtitleSwitcher plugin?

**Comment by DanielnetoDotCom** [comment]
@loso20p 

yes it is that plugin
