### ISSUE TITLE
encoder installation error

### ISSUE THREAD

**Issue by laweschan** [DanielnetoDotCom/YouPHPTube#163]
Hi,

   I have try enable encoder in private network, however, each time during installation, it hold at "processing" for a long time without any error

  I have test fresh installation at Fedora and ubuntu but no luck, I have self working streamer server
  it is strange if I input the info "https://demo.youphptube.com" during encoder installation, but when input my own streamer info it will always holding.

  is  that any hints or log that I can trace for error ?
  thanks

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
to install the encoder in a private network you must have the streamer/player on the same network.
the encoder needs to authenticate on the player before install

**Comment by laweschan** [comment]
sorry but it should already in the same network, both encoder and streamer place in the same network and only streamer has NAT mapping for outside access.
and I already add the /etc/hosts record to resolve the FQDN to internal IP, but still has no luck

thanks
Lawes

**Comment by laweschan** [comment]
yup... I guess there has a problem about authenticate on the player, can it be escape from "authenticate before install" procedure?

what is the method I have been used,
- use encoder.youphptube.com during install
- manual update the db tables and change back my own streamer with the correct auth and password 

now everything work fine ( just I can't pass the normal installation .... )

thanks
Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
Nice you got this. but the encoder need to register a player to install.
But I am happy it is working fine now.
Best regards

**Comment by brando-online** [comment]
@laweschan Thanks for posting about getting past the stalled 'Processing' modal and allowing the installation to complete - worked perfectly on my end.

However, you mentioned 'db tables' needing to be updated with the locally installed URL. Can you please let me know which tables you needed to update in the database? I will try to figure out myself while awaiting your reply, but for future users who are looking for the resolution too, I'm sure it would help a lot :)

Thank you!

**Comment by DanielnetoDotCom** [comment]
check this

![image](https://user-images.githubusercontent.com/18009293/32275683-f7fc6356-beea-11e7-8f7a-11a1cf00a704.png)

**Comment by laweschan** [comment]
yes, those tables (configurations and streamers) need update for
values..... but it just can use for the past, after git update now my
encoder cannot login now, I still not have time to find what happen, and
get a little bit confuse why always has problem

it seems not only me face to issue now, can Daniel fix to encoder
installation, or just need bypass the auth test option ?

remark:
I just found an encrypt string that use for password store (previous use
plain text format), I not sure is that co-relate, I will try a test this
week late

**Comment by brando-online** [comment]
Sorry guys, I haven't been near a computer since this morning when I last posted. I was able to get past the Encoder web installation by using your public streamer URL: https://demo.youphptube.com/ as @laweschan mentioned initially.

Now that the Stream AND Encoder web GUI install was finished, I moved onto the MySQL databases, I had to updated the two fields that @DanielnetoDotCom circled in the db tables screenshot above, they listed the 'https://demo.youphptube.com/', I replaced with my local URL: http://10.x.x.x/YouPHPTube/. 

I also updated (not sure if it matters) inside of the 'youPHPTube' database > configurations table > encoderURL to reflect my local URL too (it had the public one listed): http://10.x.x.x/YouPHPTube-Encoder/ - hoping that doesn't break anything.

I feel like there was another table field in either one of the databases that listed a non-encrypted username and password field that I updated this morning when I originally went in, but after going back in this evening, it appears they are all encrypted. I'm wondering if this is what @laweschan mentioned he noticed. However, unlike @laweschan, when I navigate to my local URL (http://10.x.x.x/YouPHPTube-Encoder/) I am still able to login to my local streamer site without issue.

Going through these steps helped resolve my Encoder installation issue.

**Comment by brando-online** [comment]
Hey @DanielnetoDotCom you should list this link under the system requirements section of your main YouPHPTube page: https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-YouPHPTube-Encoder

I had some other errors that ended up being resolved by installing a few other packages that I didn't know to install until I saw someone who completely missed it too. I had the basic LAMP stack and the individual packages listed on the main page, but not the ones like perl or curl.. and I jumped right into the video tutorial link lol. Shame on me lol

Thanks for all your help and the awesome sites/applications :)

**Comment by laweschan** [comment]
@brando-online after several tests, you need delete the plain text record in streamers tables, and then change the isAdmin value to 1 for the records with encrypt password one. 

then everything seems work, can login now

@DanielnetoDotCom it would better to include a change log / a FAQ portal, git will always update to latest and may potential break the running system, no matter what.

we like youphptube and thanks for your afford
