### ISSUE TITLE
Update to 7.0 didnt go well.. borked front page

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1643]
No video works anymore: The media could not be loaded, either because the server...

Some of the gifs are clear, most of them blurry. Some are not visible and that Play button placeholder is shown instead. In this case, gif is shrunk to top edge.

If I hover thumbnail, gif starts to play normally.
Clearing YPT and browser cache doesnt help..

![bad](https://user-images.githubusercontent.com/2082595/55865490-c758c000-5b7e-11e9-93f1-38da03963469.png)

youphptube.log doesnt show anything, no console error, php.log is empty.

**Comment by SubjectXXX** [comment]
youphptube.log doesnt show anything..

**Comment by DanielnetoDotCom** [comment]
can you please check the image URL ? and if the file exists?

**Comment by TLCReuver** [comment]
Here also blurred since last update.

URL:
http://media.beesel-reuver.nl/videos/20190402ZoektochtnaarMarjoWinkensduurtvoort_5ca45dc9965544.90232176.gif
http://media.beesel-reuver.nl/videos/20190402ZoektochtnaarMarjoWinkensduurtvoort_5ca45dc9965544.90232176.jpg

![Snap1](https://user-images.githubusercontent.com/39981177/55932872-a601dd80-5c2b-11e9-9770-00848a76ce3a.jpg)

**Comment by SubjectXXX** [comment]
Interesting, today, all is good.

I guess there was some other cache, that got cleared with timeout and I couldnt clear it yesterday on demand..
