### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by TheWebSmith** [DanielnetoDotCom/YouPHPTube#171]
After the installation I get the error:
`Specified key was too long; max key length is 767 bytes`
I'm using MariaDB version 10.1.23-MariaDB-9+deb9u1

There will be no error on MySQL 5.7+ but on everything lower that and on every
version of MariaDB the setup will get stuck.
The problem is that the limit for keys is 767 bytes for InnoDB.
A string with a length of 255 in utf8mb4 is takes more than 767 bytes.
Changing it to MyISAM would probably break the foreign keys.
I just removed line 75 of `database.sql` to be able to continue with the installation.
Maybe a hash of the column `clean_title` would work as a unique index.

**Comment by DanielnetoDotCom** [comment]
I have never see this error before, this was after or before installation?

**Comment by laweschan** [comment]
yes... using utf8mb4 will hit 4bytes issues, change in database schema is the final solution but unless developer has well test and prepare for utf8mb4, otherwise change in it may break the system.

for quick solution, you can simply update line 55, 
change from
`clean_title` VARCHAR(255) NOT NULL,
to
`clean_title` VARCHAR(191) NOT NULL,

this will allow utf8mb4 with limit to 191 char length rather than 255 char, but should keep the length limit and current beauty of coding

remark:
utf8 is utf8mb3 and using 3bytes as max
255*3 = 765 max
767 / 4 = 191 as max in utf8mb4

**Comment by TheWebSmith** [comment]
> I have never see this error before, [...]

This wouldn't surprise me at all if your database isn't using utf8 as a default charset or your version of MySQL is 5.7+.

> [..] this was after or before installation?

It was during the installation. After filling out the form `database.sql` gets executed and stop with this error when creating the table `videos`.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by rigelhope** [comment]
getting this same error with:
humhub 1.2.4
mariaDB 10.0.33
PHP 7.0.22
Ubuntu 16.04.3 LTS

then trying to open it again (because i didn't copy/paste the entire error cascade initially), it gives me the initial "click next to set up" page, and then a _different_ error, "1061 Duplicate key name 'unique_email'"

since i'm attempting to setup/provision this installation with ansible, which I'm not that proficient with, i would prefer to avoid direct changes to configuration files. the flipside of that is that i can probably reproduce the original error if more data is necessary.

**Comment by DanielnetoDotCom** [comment]
try to drop the database and try installation again

**Comment by rigelhope** [comment]
dropped the database, ran the ansible playbook again, and this time it didnt even ask me for DB credentials, which is...odd, because i'd have thought those credentials were stored in the db.

**Comment by DanielnetoDotCom** [comment]
Great :)
