### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by mili21** [DanielnetoDotCom/YouPHPTube#280]
![database error](https://user-images.githubusercontent.com/34724480/34230297-85b34614-e5cf-11e7-9d97-a51c8ef356f3.jpg)
i keep getting this database error every time i`m trying to install youPHPTube. I even did a clean install of ubuntu, drop databases so many times.... i just don`t know what is causing this issue

**Comment by DanielnetoDotCom** [comment]
We cant read the error.

can you please try to copy the whole error message and the apache log file ?

**Comment by mili21** [comment]
that`s the error.. i can`t make it smaller, i tried few times.

**Comment by DanielnetoDotCom** [comment]
try to get apache error log. this error may be there

**Comment by gamersalpha** [comment]
Hello i thini know this error : 

do this : 

4 > modifiy the source code because of old Mysql (5.0) version the databases will not created if u not modify files likes this :

sudo nano /var/www/html/YouPHPTube/install/database.sql

replace this line 52 :
clean_title VARCHAR(255) NOT NULL,
by
clean_title VARCHAR(191) NOT NULL,

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
