### ISSUE TITLE
centos 6.9 install 

### ISSUE THREAD

**Issue by fsmatt** [DanielnetoDotCom/YouPHPTube#333]
I have installed YouPHPTube on my server with no issues.  
the only thing I cant live stream. to it.  other than that no problems.  
does anyone know where i can get a RTMP-Server install for Apache httpd. 
this all i need to make it all work.  this will be a yum install

**Comment by tgd1973** [comment]
I've tried to use Centos 6.9 ... but it's more difficult because some packages concerning FFmpeg do not work perfectly with this software ... Now I have changed the operating system and this software works better ...

By the way ... the port 8080 how can you change?
I loaded the Streamer / Encoder on Ubuntu with ISPconfig that has the ControlPanel on port 8080 so I can not even use Live Streaming on the same port ... I saw that the Live plug has so many lines of code that use port 8080 .. What and where to change? Maybe for the future to consider that Live streaming uses another default port to no longer conflict with Control Panels ...

**Comment by DanielnetoDotCom** [comment]
You can change Nginx port on nginx.con file, you can choose any different port, do not have to be 8080 or 444
