### ISSUE TITLE
nginx issue in https://

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#363]
please fix....

nginx: [emerg] invalid port in url "https://www.exmple.com/plugin/Live/on_publish.php" in /usr/local/nginx/conf/nginx.conf:23

**Comment by DanielnetoDotCom** [comment]
This must be http not https

**Comment by gujarraju** [comment]
My website https installed nginx but connection issue rtmp broadcaster
connection error already set http links in plugin and nginx config file


Please help me.

**Comment by gamersalpha** [comment]
same problem here,

**Comment by tgd1973** [comment]
From what I understand the Web Server is Apache which can also be ssl (https) ... The Nginx server is used only for streaming having a different port of the Apache Web Server. The visitor who arrives, surfs on the port 80 or 443 of the Apache that in order to show people Live must have enabled a service of Proxy_Pass that reports the output of Nginx on the port of Apache ... so in Apache you have to enable this service of Proxy_Pass.

**Comment by DanielnetoDotCom** [comment]
Notice the lines https://github.com/DanielnetoDotCom/YouPHPTube/blob/4fe04a1944906b8de9ef394a8c200f707591d056/plugin/Live/install/nginx.conf#L23

must be http not https.
It works fine

**Comment by gujarraju** [comment]
Hi..
i set http not https and i am using port 8080 nginx web server is successfully installed and working
stats also ok
but brodcasting error server not connecting rtmp
i am using my website ex-: https://www.xyz.com   not http://

**Comment by DanielnetoDotCom** [comment]
the URL http://[YouPHPTubeURL]/plugin/Live/on_publish.php points to apache/streamer site, not nginx

**Comment by hersche** [comment]
there's no more activity, i think that's done. like always, reopen when i am wrong.

**Comment by pkapoor86** [comment]
fail to connect to server 
![Screenshot from 2020-05-01 11-27-29](https://user-images.githubusercontent.com/38718728/80785725-daca3500-8b9e-11ea-9db4-143fd47b72c7.png)
