### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by ghost** [DanielnetoDotCom/YouPHPTube#364]
In the repository there's a `LICENSE` file containing the AGPL. It says:

>This License explicitly affirms your unlimited
>permission to run the unmodified Program.

However in `README.md`, you say:

>This Software must be used for Good, never Evil. It is expressly forbidden to use YouPHPTube to build porn sites, violence, racism or anything else that affects human integrity or denigrates the image of anyone.

Which is contradictory, so the license is unclear. Besides that a phrase like that makes YouPHPTube not open source, since the Open Source Definition says:

>The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it, I am looking for a better license that.
I really do not want to support "bad used" sites.
If anyone has any idea, please help me

**Comment by TheAssassin** [comment]
@DanielnetoDotCom well, one core property of free software is that users can do what they want to with the software. Your license and your, let's call it, "wish", contradict here. This leaves users of the software in a legally unclear situation. There is no "default legal definition" of what "good" is, neither what "bad" is. And you don't describe either term. Furthermore, the list of what's prohibited to use the software for is problematic. Imagine someone puts a recording of a comedy show on a page, where people are insulted ironically. Theoretically, this could violate your list of forbidden content.

I personally think that if you want to develop free software, you need to ensure users' freedoms. Check out https://www.gnu.org/philosophy/free-sw.en.html for a list of the "4 freedoms" of software, especially freedom 0:

> The freedom to run the program as you wish, for any purpose (freedom 0).

Another reason to remove the restriction is that in theory, you are imposing users of your software (a.k.a. hosters of YouPHPTube) a liability for the content their users upload. Do I need to actively monitor _all_ videos ever uploaded? Do I have to stop using YouPHPTube the day someone uploads a violating video, or can I redeploy the site once the content has been removed?

This all is a legal nightmare, and I'm pretty sure that in case of a violation you wouldn't have any legal right to force someone to take down their page, as your license grants them a right to do whatever they want to.

But, after all, in my experience it's really hard to enforce your rights as a copyright holder even with the lack of such restrictions. Check out one of the other projects I (and, by coincidence, @wb9688) work on, NewPipe: https://github.com/TeamNewPipe/NewPipe/issues/539

**So, my recommendation: Remove the restriction.** It's most likely not valid legally. Instead, you should write something like "while this is free software, please do not <stuff>", calling upon people's fairness.

**Comment by TheAssassin** [comment]
By the way, did your contributors even agree to changing the license overnight? Every contribution before the date of [this commit](https://github.com/DanielnetoDotCom/YouPHPTube/commit/0e21a4119b8c6935e459ad2b1f0d4d1b6fbcb10e#diff-9879d6db96fd29134fc802214163b95a) does _not_ fall under the terms of the JSON license. You can't simply _change_ your license, buddy, you need their consent, or declare any code that has been published before this date as AGPL. Not to mention that all the files that these authors _ever_ touched are AGPL as well, due to the copyleft restriction. As you didn't add any of these declarations, you are breaking the copyright law.

This is really a nightmare, legally. I would recommend you to get professional support in order to avoid legal consequences.

**Comment by adam993** [comment]
> I really do not want to support "bad used" sites.
I see that you are a very religious person and wouldn't like your work to be used for something you and the Bible consider bad.
Consider this: God is omnipotent, so He can do anything and everything. Yet, He allows evil to exist. Why? Because in order to maximize good in this world, free will must be given to all, wicked and good alike. 
Bottom line - you shouldn't worry about how your software is used, because majority will use it for good (after all people are mostly good, only a small percentage would use your code to make porn website or something similar.). Some of the people WILL use your code for something you consider wicked, but God  would like you to allow that in order to permit free will :)

**Comment by DanielnetoDotCom** [comment]
Hi @adam993 

The free will exists, also the free will for my decision to not support bad sites and the free will for people to disrespect my decision.

I forgive those who have disrespected me, but I do not support them.

> They say to him, Master, this woman was taken in adultery, in the very act.
> Now Moses in the law commanded us, that such should be stoned: but what say you?
> This they said, tempting him, that they might have to accuse him. But Jesus stooped down, and with his finger wrote on the ground, as though he heard them not.
> So when they continued asking him, he lifted up himself, and said to them, He that is without sin among you, let him first cast a stone at her.
> And again he stooped down, and wrote on the ground.
> And they which heard it, being convicted by their own conscience, went out one by one, beginning at the oldest, even to the last: and Jesus was left alone, and the woman standing in the middle.
> When Jesus had lifted up himself, and saw none but the woman, he said to her, Woman, where are those your accusers? has no man condemned you?
> She said, No man, Lord. And Jesus said to her, Neither do I condemn you: go, and sin no more.
> 
> João 8:4-11

**Comment by TheAssassin** [comment]
The core issue is the inconsistency in the licensing, I'd say. This should be resolved quickly. You could just edit the current license and make your changes, then call it "YouPHPTube license 1.0". The README and other documents shouldn't contradict the LICENSE file. Oh, and please make sure that parts of the license don't contradict others. If in doubt, I'd recommend you to get professional advice.

**Comment by nickian** [comment]
This license makes no sense has no legal basis. "Good/evil" is a vague and subjective concept. Maybe "good" is absolute freedom for people to distribute any type of information on an open and transparent internet. And "evil" is having the audacity to impose one's personal beliefs on others.

Why don't you just use something standard like the MIT license?

**Comment by SubjectXXX** [comment]
Because MIT is not written on religious stance..

Only workaround for this problem of integrity is to remove opensourcesness and do it like a freeware with mandatory registration and author's approval. That will only satisfy author tho.

In any case, this "licence addon" of bad sites or usage for bad intentions is not user bounding, thus its not a valid licence clause and can be simply ignored by users. No legal actions can be taken against users that use this software for "bad sites" anyway.

**Comment by hdavy2002** [comment]
I am not into the legal aspects of the license. However, ethically speaking. The creator and his wishes should be respected ethically. A good tree will produce good fruit and a bad tree will produce bad fruits. Morally we are bound by open source license, (if one goes public with his code) and so good people will use it for good and bad people will use it for bad sites. All I can add , whoever uses this software. Please keep creators wishes in mind. He worked hard to bring this free project to light.

**Comment by DanielnetoDotCom** [comment]
Thanks so much @hdavy2002

**Comment by yowee** [comment]
what you gonna do if somebody uses for evil purpose ? how can you stop them ?

**Comment by TheAssassin** [comment]
@yowee you can't, that's the point. The whole sentence is legally invalid. As suggested earlier, it should be removed from the license and put elsewhere, clearly stating that this is a wish that should be respected. Most people would respect that. Some never will. But then, legally, things are clear.

**Comment by ds6** [comment]
@DanielnetoDotCom is clearly ignoring any and all advice in regards to this poor licensing. The phrase

> The Software shall be used for Good, not Evil.

is entirely subjective and not legally enforceable. What is "Good"? What is "Evil"? The terms are not defined in the document, are generic and ambiguous, and would surely be found to be not legally binding in a court of law. You may find that, when given respectfully, one's wishes may be followed, eg. to ask people to not use your code for things you does not morally support, instead of trying this hamfisted approach... But that's beside the point.

As the copyright holder to your own code and of the project (or as much as is enforceable by your own local laws and statitutes), you are free to license them under whatever terms you like. However, you are not the sole contributor, and as such do not have full copyright over the entire codebase. [You should have contacted all of these people to get their explicit permission to have their code relicensed to the AGPL](https://github.com/DanielnetoDotCom/YouPHPTube/graphs/contributors?from=2017-04-02&to=2017-09-11&type=c), which while compatible does add restrictions to the GPLv3 that someone might not agree with. Furthermore, [these people should have been contacted for consent for the switch to the JSON license](https://github.com/DanielnetoDotCom/YouPHPTube/graphs/contributors?from=2017-09-11&to=2018-02-16&type=c), which is _not compatible with the GPLv3_.

While this may not seem like a big deal, if they did not/do not consent to these changes, you are not meeting the requirements of the GPL/AGPL, and are likely violating their local copyright laws. Any of them that do not consent may at any time take you to court, or at the very least demand their code be scrubbed from the repository with good reason.

As far as I have seen you have not specified any contributor provisions or agreements specifying their copyright over their work to be transferred to you or some other rightsholder, so you have _zero legal precident_ to do what you've done. It's not cool and spits in the face of free software.

Will anything bad happen? Probably not, but just like you want to be in the moral right by defending your project from being used for "bad use"-sites, you should do what is morally right for your contributors, and even if they don't care, you should set a good example for others to follow. Isn't that the righteous way? :smirk:

I highly recommend you read [the](https://github.com/DanielnetoDotCom/YouPHPTube/blob/440c70c651340140d35e83a7cdc745c116598f17/LICENSE) [licenses](https://github.com/DanielnetoDotCom/YouPHPTube/blob/67577e40e18b05c14968a9b753b892924b8af2d5/LICENSE) you used, as well as [The Developer's Guide To Copyright Law](https://haacked.com/archive/2006/01/24/TheDevelopersGuideToCopyrightLaw-Part1.aspx) by Phil Haack, or at least [part 3](https://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx).  
Like him, I am not a lawyer.

**Comment by Methen** [comment]
Basically what it comes down to is what the owner of the software is asking  is not possibile, You see the true defintion  of good and evil really comes down to one very simple word and that word is opinion, in short he is asking you not to use the software based on his opinion of what is Good or Bad,, Which is simply not possibile, I can understand where he is coming from to a degree I would be very upset of someone were to use something I created that was highly offensive to me, But sadly that is just the way it is in this world...

**Comment by Methen** [comment]
Ps the edit feature here does not appear to work
