### ISSUE TITLE
Can't run on windows server.

### ISSUE THREAD

**Issue by usmanshahzadmax** [DanielnetoDotCom/YouPHPTube#425]
Hi there!
I'm using windows base server and there .htaccess files are not supported instead of that they support web.config files. 
It's not even installing in my server. Please do let me know if you have anything to fix this issue...
Thank you so much...
Looking forward to hear back from you..
Regards...

**Comment by DanielnetoDotCom** [comment]
Hi

we do not support windows, but streamer site may work

I dont know web.config file.

You will need to compile some sources, Plesk will not let you do this.

**Comment by usmanshahzadmax** [comment]
Hi Daniel !

Thanks for the quick response. Is there any way to fix this problem or a
way to convert the .htaccess file to web.config, if possible...?
Regard.

**Comment by usmanshahzadmax** [comment]
This is the error massage I'm getting..
Error. Oops you've encountered an error
It appears that either something went wrong or the mod rewrite configration is not correct.
We need to allow Apache to read .htaccess files located under the G:\PleskVhosts\wakeuppk.com\test1.wakeuppk.com directory. You can do this by editing the Apache configuration file:

Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

sudo nano /etc/apache2/apache2.conf
After editing the above file your code should be like this:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
In order to use mod_rewrite you can type the following command in the terminal:

sudo a2enmod rewrite
Restart apache2 after

sudo /etc/init.d/apache2 restart
or

sudo service apache2 restart

**Comment by DanielnetoDotCom** [comment]
Sorry but I dont know web.config.
Anyway I could use YPT with Xampp on windows

**Comment by DanielnetoDotCom** [comment]
We recommend apache to host YPT

**Comment by hersche** [comment]
hello, i am working on implement a php-router.

according to the docs, it would be quite easy for iis:
https://github.com/skipperbent/simple-php-router#setting-up-iis
also, the web.config is already delivered on downer branch.

because this needed a lot of editing, proper testing would be nice. at the moment, i know nothing, that does not work, but i am far away from testing everything.

anyone who would like to join testing can find the source here:
https://github.com/DanielnetoDotCom/YouPHPTube/tree/php-router

there is also a live-demo with the new code (on apache!), if you would like to test, but not waste time in install it. just say the username here and you will get admin after i see it..
https://rewrite.codebea.ch/

**Comment by hersche** [comment]
@usmanshahzadmax @hypedboss there should be some experimental support now. feedback would be nice, i don't like to test this (i dislike microsoft)

**Comment by hersche** [comment]
closed due to inactivity. reopen if it does not work.
