### ISSUE TITLE
How to upload audio file (mp3) ?

### ISSUE THREAD

**Issue by nbenm** [DanielnetoDotCom/YouPHPTube#429]
Hello,

I know how to upload video file, there's a button "My videos" / "upload a mp4 file".
This works fine.
But I haven't found how to upload an audio file.
I have converted with ffmpeg a mp3 file to mp4, and then uploaded it. The problem is that it is stored as video, not audio. Second, it has an empty image (snow).
What is the good way to upload a mp3 file ?
Thanks

**Comment by DanielnetoDotCom** [comment]
Audio upload is not working now.
It will be fixed soon.

**Comment by hersche** [comment]
hello, i just make this working for me, if someone wants to test it, it's there: https://github.com/hersche/YouPHPTube/tree/unstable

direct upload (mp4 upload in streamer) works for me, optimised only youphpflix and made a option "separateAudio" there..

the upload needs pre-converted mp3's or ogg's (ogg's are untestet, i did only mp3's) - mp4 means video as ever..

**Comment by DanielnetoDotCom** [comment]
@hersche is it working on the Pull request 5.0?

**Comment by hersche** [comment]
nope, it's still in the unstable-branch, cause there could be error's i've not seen yet.

if you can test it as well, it would be nice.

https://github.com/hersche/YouPHPTube/tree/unstable

btw-offtopic: at the moment i'm making progress on sub-categorys..

**Comment by DanielnetoDotCom** [comment]
Great, I will make some tests

**Comment by hersche** [comment]
cool.

there's a option in youphpflix, called separateAudio. i suggest you to test this as well, i hope you like the result (still not finished, can be as much extendet like videos are now)

**Comment by nbenm** [comment]
Hello,

I’ve tried to install new version.
I had some errors, I don’t remember which, so I decided to re-create database.
I’ve drop the older manually.
Now I cannot create the new one. Categories table has changed. « description » field has lo default value.
« checkConfiguration.php » rises an error.

**Comment by DanielnetoDotCom** [comment]
@nbenm I will test here

**Comment by DanielnetoDotCom** [comment]
@nbenm I just sent a fix for this, please drop your database again, make a git pull command and try to install again

**Comment by nbenm** [comment]
I did a:
git clone https://github.com/hersche/YouPHPTube.git

and now a git pull says already up to date.
What I’m I doing wrong ,

**Comment by DanielnetoDotCom** [comment]
@hersche it is fixed now :)

**Comment by hersche** [comment]
yeah, i did a PR from your master to my unstable-branch and merged it, so i have your fix :)
thanks but sorry.. don't like to break the installations..

what do you think about the other changes?

**Comment by nbenm** [comment]
@hersche Sorry, I get same error

**Comment by hersche** [comment]
@nbenm do you try with a fresh db?
i've not tested a new installation again, just merge the commits..
if it's not a fresh db, it's important to update. but i like to test it quickly if a fresh installation works for me.

**Comment by nbenm** [comment]
I use a mysql server containing other db.
But I have dropped YouPHPTube db
I have also restarted the Apache server
Can it be cache related ?

**Comment by hersche** [comment]
if you just do the checkout, maybe clearing cache helps (the folder is not reconized by git)

i just tested it again, successfull installed in xampp..

i have also a effect that when i clear my videos-folder, that i have to reset the ownership to www-data or make it chmod 7777..

you did git pull in the folder again, since i wrote this about fixing?

i'm sorry when i ask like this, but maybe it's a small forgotten thing..
and my local installation needed the _youphp-url/update_ to show videos again (after merge the fix), but after the update it was working again..

**Comment by nbenm** [comment]
@hersche I have removed the YouPHPTube folder, and then did a git clone 

Here’s the insert instruction in checkConfiguration.php:
$sql = "INSERT INTO categories (id, name, clean_name, created, modified) VALUES (1, 'Default', 'default', now(), now()) »;
As you can see, there’s no value for description column.
In the create table there’s no default value.

I have a script in crontab that does chown www-data:nb and chmod -R 770 every minute

I will have a closer look at this tomorrow. It’s late here, I’m going to sleep.

**Comment by hersche** [comment]
i've pushed it to unstable, but not testet.

**Comment by nbenm** [comment]
@hersche I was on master branch.
Installation works fine now.
I have uploaded a mp3 file. There was no need to convert it to mp4 as it was in the past.
Nice player...
I haven't seen any issue for the moment.
Good job!

**Comment by hersche** [comment]
i did another update this night, it will need some stabilisations, i try to collect this here, but first explain the idea: we found it cool to be able to separate audio-categorys and video-categorys.
since this is not always needed and i don't want to make the categories-table too fat, i made a separate "cache"-table for this.

there are 4 modes, you can set in mcategorys: auto, both, audio, video. if this is NOT auto, it's fully manual and will NOT do react on save video (down).

auto will decide, what kind of category it is, when you save the video (and move audio or video to another category). auto can then be both, audio and video. at the moment, this goes through subcategorys as well and works well for single categorys when you open edit and save once too much. set it static should work withouth problems.
glyphicons / icons in category-gallery in youphpflix should show a audio-symbol instead of cd when audio only (little proof of concept) and disable audio-gallery in cat when cat-type is video.

i think the diffrence between manual and auto should be intuitive, but maybe i am wrong, would be interessting to have feedback there..

todo there:
* auto-update old category-type (only new will be saved after move) as well, when save video
* auto-update category-type by changing back to auto in mcategories
* make more use of the category-type in view's

**Comment by nbenm** [comment]
I don't understand how categorie work.
I have created category "cat1" and the tried to create category "cat11" with Parent-Category "cat1".
It wasn't possible. I could choose only between "None" and "Default"

A question: you often talk about youphpflix, what is it?
4 avril 2018 03:49 "Vinzenz Hersche" <notifications@github.com (mailto:%22Vinzenz%20Hersche%22%20<notifications@github.com>)> a écrit:
	i did another update this night, it will need some stabilisations, i try to collect this here, but first explain the idea: we found it cool to be able to separate audio-categorys and video-categorys.
since this is not always needed and i don't want to make the categories-table too fat, i made a separate "cache"-table for this. 

	there are 4 modes, you can set in mcategorys: auto, both, audio, video. if this is NOT auto, it's fully manual and will NOT do react on save video (down). 

	auto will decide, what kind of category it is, when you save the video (and move audio or video to another category). auto can then be both, audio and video. at the moment, this goes through subcategorys as well and works well for single categorys when you open edit and save once too much. set it static should work withouth problems.
glyphicons / icons in category-gallery in youphpflix should show a audio-symbol instead of cd when audio only (little proof of concept) and disable audio-gallery in cat when cat-type is video. 

	i think the diffrence between manual and auto should be intuitive, but maybe i am wrong, would be interessting to have feedback there.. 

	todo there: 
	* auto-update old category-type (only new will be saved after move) as well, when save video 
	* auto-update category-type by changing back to auto in mcategories 
	* make more use of the category-type in view's

**Comment by hersche** [comment]
> I don't understand how categorie work. I have created category "cat1" and the tried to create category "cat11" with Parent-Category "cat1". It wasn't possible. I could choose only between "None" and "Default"

ok, i assume, this is because it needs the subcategory-list does not update after creating or rename a category. so, after create/modify, reload the site and you should find it - is that right?

but thats a point which is unfinished and confusing yet..

**Comment by hersche** [comment]
now, i've fixed also all plugins for audio, make some other fixes with cover, cleaner code, etc.

a answer would be really interessting, i would say, it's ready to merge.. but i need feedback, about the ideas / how it's solved and also bugs.

**Comment by hersche** [comment]
for the moment, main-branch is changed to master..
the reason is here: #563

**Comment by nbenm** [comment]
I think this issue can be closed now thanks to Hersche
