### ISSUE TITLE
Please Help, tmp folder not found

### ISSUE THREAD

**Issue by hypedboss** [DanielnetoDotCom/YouPHPTube#590]
PHP Warning: file_get_contents(/tmp/1bcd918b88e3338492b39e5bcaee1bd3.gif): failed to open stream: No such file or directory in /home/webbiwoo/public_html/convert/objects/getImageMP4.php on line 66

**Comment by DanielnetoDotCom** [comment]
I dont know why this happened, can you please create the /tmp dir?

**Comment by hypedboss** [comment]
in public_html?

**Comment by hypedboss** [comment]
It's still the same

**Comment by nightstryke** [comment]
@hypedboss That's not what he meant, if you have access to the server make sure the user that is running youphptube has access to the /tmp/ folder in the main Linux Root. If you do not have access or cannot configure otherwise you need to get a different provider that will allow you access. For example, rent a vps or dedicated server instead of using a shared hosting account.

**Comment by hypedboss** [comment]
Am using vps not shared hosting

**Comment by nightstryke** [comment]
depending on your linux version login to the user and use sudo su to get root access and then type `cd /tmp` to see if the folder exists if it does not you may need to create it. `mkdir /tmp`

**Comment by hypedboss** [comment]
Please can you help me if i forward you my vps details?
