### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mobber007** [DanielnetoDotCom/YouPHPTube#60]
Hey guys,

I was trying to install YouPHPTube, but i can't get trough with it because of this issue:
"Error deleting user: Cannot delete or update a parent row: a foreign key constraint fails (`youPHPTube`.`configurations`, CONSTRAINT `fk_configurations_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)"

Is there a fix for this?

Thank you

![screenshot 2017-07-07 20 21 15](https://user-images.githubusercontent.com/21088800/27969047-0ae8bc7a-6352-11e7-9351-6ff66cc47327.png)

**Comment by DanielnetoDotCom** [comment]
Try to manual delete YouPHPTube database before install

Em 7 de jul de 2017 14:23, "mobber007" <notifications@github.com> escreveu:

Hey guys,

I was trying to install YouPHPTube, but i can't get trough with it because
of this issue:
"Error deleting user: Cannot delete or update a parent row: a foreign key
constraint fails (youPHPTube.configurations, CONSTRAINT
fk_configurations_users1 FOREIGN KEY (users_id) REFERENCES users (id) ON
DELETE NO ACTION ON UPDATE NO ACTION)"

Is there a fix for this?

Thank you

[image: screenshot 2017-07-07 20 21 15]
<https://user-images.githubusercontent.com/21088800/27969047-0ae8bc7a-6352-11e7-9351-6ff66cc47327.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/60>, or mute the
thread

**Comment by mikweb2017** [comment]
Try phmmyadmin more permissions for the user for the database

**Comment by alexynior28** [comment]
Hi, I have the same problem. Tested on fedora 25.
An additional problem is that I add the chmod R - 777 permission ... and it just does not recognize me.

Please help.
Sorry if you do not understand, I do not speak an expert English.
![screenshot_20170830_144900](https://user-images.githubusercontent.com/19245743/29897654-9f82e868-8da7-11e7-850c-724839497cf7.png)
![screenshot_20170830_165211](https://user-images.githubusercontent.com/19245743/29897631-7eebf1e4-8da7-11e7-905c-51d6fe24736c.png)

**Comment by DanielnetoDotCom** [comment]
Hi 

About the command you are using the wrong one, the correct command is: 

`chmod -R 777 /path-to-youphptube/videos/`

about the database error, try to drop the database and try again

**Comment by alexynior28** [comment]
Hello,

Of course, in my case I have colfaced chmod -R 777 /var/www/html/YouPHPTube/videos/ And it does not show me any error, I even changed the previous command by  chmod -R ugr+rwx /var/www/html/YouPHPTube/videos/

On the database (which gave me error in deleting user) I have pasted ON DELETE CASCADE into the table {configurations} , and it deletes it correctly. Now, when I click submit (on localhost/YouPHPTube) I no longer see an error, but nothing is created either.

Does it have to do because permissions (in chmod) flag error, or is it a database subject? In other words, can it still work if an error is marked (left color highlighting) in the permissions?

**Comment by alexynior28** [comment]
Here I leave my catch
![screenshot_20170830_222914](https://user-images.githubusercontent.com/19245743/29905199-c92eb432-8dd2-11e7-9c63-64a26042f05c.png)

**Comment by DanielnetoDotCom** [comment]
check this command
ls -lah /var/www/html/YouPHPTube/
check if the videos directory permition (place a printscreen if you can)

if the permition is ok try to ignore this error

**Comment by alexynior28** [comment]
Apparently yes:
drwxrwxrwx.  2 root root 4,0K ago 30 15:50 videos

![screenshot_20170901_105148](https://user-images.githubusercontent.com/19245743/29977736-0aef69d4-8f04-11e7-89ac-ba2721efcec1.png)

On the other hand, the only thing I modified the database.sql file is the following:
ON DELETE NO ACTION> ON DELETE CASCADE

![screenshot_20170901_110447](https://user-images.githubusercontent.com/19245743/29978096-66d85c0a-8f05-11e7-8711-ba7549b3def5.png)

![screenshot_20170901_110550](https://user-images.githubusercontent.com/19245743/29978152-91f0dc0a-8f05-11e7-9f39-f12ad1c00c87.png)

Because it caused me error when deleting a user and creating a new one (as in the initial image capture)

It looks like it already causes me an error, but it does not update me at all and stays on the same installation screen.

Do you have any idea what might happen? first of all thanks for that wonderful work :)

**Comment by DanielnetoDotCom** [comment]
There is a way I can try to install it for you?
Even better if you can give me ssh access to it.
send me an email if you can developer@youphptube.com

**Comment by alexynior28** [comment]
Ok I'll send you a message. Thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by datmau** [comment]
I have the same problem in a recent installation of the Ubuntu server that deals with the root user and I create another user with all the privileges, but it does not work. I have already tried with "DROP Database name" and trying again. And also by giving another name to the database. Is there any other alternative?
![seleccion_066](https://user-images.githubusercontent.com/29211422/42149247-07465834-7d9b-11e8-89b7-ff72d3f1ed11.png)

**Comment by DanielnetoDotCom** [comment]
What database name are you using?
Just to make sure the script is running correctly, is it youPHPTube (case sensitive)?
Does this table exists?

**Comment by datmau** [comment]
I have used several names, none of them works, anyway it returns the same error. 
If I place the first option to create database and tables, only the base is created and the error returns. If I create the base manually and I put create tables (second option) it returns the same error. If I run manually the script returns something like this.
![seleccion_067](https://user-images.githubusercontent.com/29211422/42170701-e7699c50-7ddc-11e8-9a1a-14f65283aad9.png)

What is your recommencement to follow? Thanks in advance

**Comment by DanielnetoDotCom** [comment]
We fixed an issue related to externalOptions this morning. can you please check if you have the latest version?

@Criptos do you have any idea?

**Comment by Criptos** [comment]
No concrete idea, just an apology. 
I ll do some test with the tool I used to detine the table..

**Comment by DanielnetoDotCom** [comment]
@Criptos no problem I guess it is sloved

**Comment by honeyfairy** [comment]
Same problem here

**Comment by praveenokia** [comment]
> Here I leave my capture
> ![screenshot_20170830_222914](https://user-images.githubusercontent.com/19245743/29905199-c92eb432-8dd2-11e7-9c63-64a26042f05c.png)

chmod 777 /var/www/html/YouPHPTube/videos

**Comment by DanielnetoDotCom** [comment]
@piotrekkr I guess you are not using ubuntu, but anyway, you can ignore it and continue.
