### ISSUE TITLE
Bypass encoding if the video is already in WebM format

### ISSUE THREAD

**Issue by tiagostutz** [DanielnetoDotCom/YouPHPTube#66]
Hi!
I'm wondering whether it would be possible to bypass the encoding phase if the video was already in the correct format. I mean, if the user is somewhat advanced and have the tools to convert the video to WebM before uploading it, there could be this feature, which would make the publishing task bit faster and the server would have less work to do, in such cases.
Does that make sense?

**Comment by DanielnetoDotCom** [comment]
yes it make sense for me, but for now it is not possible

**Comment by tiagostutz** [comment]
Are you open to collaboration on this?
Also, in the last version I noticed some layout breaks I can work on that too... any guidelines on this or can I just make it and send a Pull Request?

**Comment by DanielnetoDotCom** [comment]
Sure this will be great
I really need collaboration on this.
I am waiting your pull request

**Comment by tiagostutz** [comment]
PR available! =)

I'm using Docker in the development here, but I'm having trouble with logging. The logs just don't appear at the docker logs. I tried a lot of things with no success... I was wondering whether you are working with Docker too and more precisely, how are you dealing with log, where are the log files, what are the functions you call and how.... Thanks!

**Comment by oyjcmyn** [comment]
Hope that the player can become more perfect, so that experience better.
In fact, you can also use third-party open source video player, for example
clappr:Support MP4 flv m3u8, support subtitles, support for high-definition options.
[https://github.com/clappr/clappr](https://github.com/clappr/clappr)

dplayer:Support MP4 flv m3u8, support high-definition options, support barrage.
[https://github.com/DIYgod/DPlayer](https://github.com/DIYgod/DPlayer)
