### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by ryankel91** [DanielnetoDotCom/YouPHPTube#731]
hello all i really need help on my this i was trying to upload a page on my shell and i saw this i need help please {HEX}php.malware.magento.597.UNOFFICIAL FOUND

**Comment by hersche** [comment]
i also never saw this. did it tell, which file it means or any details?
what antivirus-programm told you this?

**Comment by gkooistra** [comment]
Hello ryankel91,

Do you run a magento webshop on your server?
If you do, than I advise you to search there for the problem.

**Comment by hersche** [comment]
this seems to be kind of duplicate #274 , means it's about paid and therefore encrypted plugins. therefore, it's difficult to analyse those plugins, i think.

the issue leads to https://github.com/rfxn/linux-malware-detect/issues/263

so, this is a fake-message because the antivirus-developers ignoring the issue.

i close it, because that has to be done in the antivirus, not youphptube.
