### ISSUE TITLE
new install: Fatal error: Uncaught Error: Call to a member function close() on null

### ISSUE THREAD

**Issue by khancyai** [DanielnetoDotCom/YouPHPTube#769]
Hi, 

I just install it on godaddy shared hosting and getting this error message what is wrong didn't understand can you help please?

Notice: Trying to get property 'nCols' of non-object in /home/user_machine_name/public_html/objects/mysql_dal.php on line 335

Notice: Trying to get property 'stmt' of non-object in /home/user_machine_name/public_html/objects/mysql_dal.php(341) : eval()'d code on line 1

Warning: mysqli_stmt_bind_result() expects at least 2 parameters, 1 given in /home/user_machine_name/public_html/objects/mysql_dal.php(341) : eval()'d code on line 1

Notice: Trying to get property 'stmt' of non-object in /home/user_machine_name/public_html/objects/mysql_dal.php on line 173

Fatal error: Uncaught Error: Call to a member function close() on null in /home/user_machine_name/public_html/objects/mysql_dal.php:173 Stack trace: #0 /home/user_machine_name/public_html/objects/configuration.php(58): sqlDAL::close(false) #1 /home/user_machine_name/public_html/objects/configuration.php(45): Configuration->load() #2 /home/user_machine_name/public_html/objects/include_config.php(19): Configuration->__construct() #3 /home/user_machine_name/public_html/videos/configuration.php(39): require_once('/home/h7cta0poa...') #4 /home/user_machine_name/public_html/view/index.php(16): require_once('/home/h7cta0poa...') #5 {main} thrown in /home/user_machine_name/public_html/objects/mysql_dal.php on line 173

**Comment by DanielnetoDotCom** [comment]
can you please paste your streamer error log here?

BTW, we recommend installation on a VPS or dedicated server, a shared host may not work properly

**Comment by khancyai** [comment]
I solved with clean install. Thx.

**Comment by hersche** [comment]
also, big daddy's shared hosting does not support the mysqlnd-driver. we have a fallback there.

it's to say, that it's more performant with a host, where mysqlnd is avaible.

**Comment by gdulli111** [comment]
Hi,

I just install it on hostgator shared hosting and when i activate the live plugin and click on live instead of seeing the live setting page I am getting this error message not sure what is wrong I didn't understand any help will be much appreciated, anyone please ?

Here is the error copied it.

Warning: mysqli_stmt_bind_result() expects at least 2 parameters, 1 given in /home2/gdulli101/public_html/stream/objects/mysql_dal.php(354) : eval()'d code on line 1

Fatal error: Uncaught Error: Call to a member function close() on null in /home2/gdulli101/public_html/stream/objects/mysql_dal.php:185 Stack trace: #0 /home2/gdulli101/public_html/stream/plugin/Live/Objects/LiveTransmition.php(102): sqlDAL::close(false) #1 /home2/gdulli101/public_html/stream/plugin/Live/Objects/LiveTransmition.php(115): LiveTransmition::getFromDbByUser(1) #2 /home2/gdulli101/public_html/stream/plugin/Live/index.php(76): LiveTransmition::createTransmitionIfNeed(1) #3 {main} thrown in /home2/gdulli101/public_html/stream/objects/mysql_dal.php on line 185
