### ISSUE TITLE
404 ERROR

### ISSUE THREAD

**Issue by cespa92** [DanielnetoDotCom/YouPHPTube#771]
Hello Daniel, I installed on Google Cloud Virtual Server, and I finished the Installation and I try acces to login and got the error 404

Here my installation Link: http://104.196.137.193/YouPHPTube/

and by the way for LIVE VIDEO, I need buy a plugin? Thanks

**Comment by hersche** [comment]
![non404-screenshot_20180617_111751](https://user-images.githubusercontent.com/90995/41506543-228808b2-7220-11e8-9bad-c3b0aefec793.png)

i don't see that.. it just appears.. solved for you already?

**Comment by cespa92** [comment]
Hello Hersche, try access to login page, still I have the problem... Thanks!

**Comment by DanielnetoDotCom** [comment]
Hi

How did you put the files on your server ?

Did you use git clone command?

Or you upload the files?
If you upload are you sure you upload all files?

**Comment by cespa92** [comment]
I installed following the instructions of video on youtube for install on Ubuntu server of Danielneto + Info (commands) Wiki from here Github...

**Comment by cespa92** [comment]
Thankd Hersche, It's SOLVED...

**Comment by cespa92** [comment]
Hersche, a question, how can I change the URL of http://104.196.137.193/YouPHPTube/ to http://mydomain.com --- Really thanks!

**Comment by cespa92** [comment]
Hersche a question how can I change the URL of http://104.196.137.193 to http://mydomain.com - really thanks!

**Comment by hersche** [comment]
nice :)

@DanielnetoDotCom that's a side-effect of the php-router - the .htaccess is there, but the rewrite-module for apache is not installed.. when we force this check, php-router get's unuseable (for nginx for example).

maybe put a warning on installation can be good?

@cespa92 

that's relative easy, go to the file "videos/configuration.php". there, edit the line begin with

    $global['webSiteRootURL']

i let the bug-report open, because the effect of 404 is a good description.

**Comment by hersche** [comment]
i copied the "error"-wiki-site to the howtos, so there's the description how to enable the rewrite-modules, as well.. :)

so it's closeable..
