### ISSUE TITLE
New install: "Connect Error (1698) Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by MarkOnDuty** [DanielnetoDotCom/YouPHPTube#794]
Trying to get a new install up and running. I'm following the instructions for Ubuntu 18.04.

When clicking submit on the installation page, I get "Sorry! Connect Error (1698) Access denied for user 'root'@'localhost'. This looks like a MySQL error.

I may have submitted the YouPHPTube-encoder installation page before the YouPHPTube installation page.

Update:  This was on Ubuntu Server 18.04 LTS. On 16.04 LTS, I get asked to choose a password for the root MySQL user during package installation. That does not occur on 18.04 LTS, which I suspect is the problem.

**Comment by hersche** [comment]
> This was on Ubuntu Server 18.04 LTS. On 16.04 LTS, I get asked to choose a password for the root MySQL user during package installation. That does not occur on 18.04 LTS, which I suspect is the problem.

that can be very well, on some distros, i had that.. "reset mysql root password" is a good google-search for this.. my expirience is, that you can login with root-user via command-line (no need for password) and set it there..

a special thing for me was, that on root-user, in the plugin-column, it was set to "unix" - empty this column, it restrict the user to the command-line.

i can be wrong in case of ubuntu 18.04 (maybe it's much easier possible), but at least for some other debian-based-systems, that's true..

but it is not a direct problem of youphptube. i recommend you to place phpmyadmin somewhere and try to log in there. when it works, it should also work for youphptube. 

i recommend phpmyadmin because i think it's very well tested and kind of referrence for me.

**Comment by hersche** [comment]
sudo mysql_secure_installation

does this work for set your root-password? google is nice..

**Comment by hersche** [comment]
please do a update / git pull, i fixed a nasty bug.

**Comment by MarkOnDuty** [comment]
Will do. Thanks.

I was pretty sure that was the issue, and it has been confirmed elsewhere. I'll give an install on a fresh 18.04 container a try and close this issue if it works.

**Comment by MarkOnDuty** [comment]
I got the same problem this morning, even after setting a root password via `sudo mysql_secure_installation`. I'm not sure why it didn't set the passphrase, but it is definitely blank in the mysql.user table.

I had to set the root passphrase manually, via the `mysql` client:

`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'tNcGrTdsr0k2tT4eMY5C';`

This can also be done from the command-line:

`sudo mysqladmin -u root OLDPASSWORD NEWPASSWORD`

After dealing with this, I was able to work through the rest of the setup. Everything seems to have worked properly and I'm at the point where I can upload videos. I consider this issue closed, although a comment in the install notes might avoid some trouble.

**Comment by hersche** [comment]
i've added it as a "if mysql_secure_installation not works" to the doc.

i think, this mysql_secure_installation is the official way, so i let it stay..

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

**Comment by orangereddy** [comment]
well iam getting like this can anyone help me in this issue please help me
<img width="1440" alt="Screenshot 2020-03-31 at 12 38 09 AM" src="https://user-images.githubusercontent.com/33618843/77958199-4bf1a080-72f2-11ea-84e9-6caabfab537f.png">

**Comment by akhilleusuggo** [comment]
@orangereddy 
```
sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'NEWPASSWORD';
```

**Comment by orangereddy** [comment]
thank you @akhilleusuggo it’s working sir
