### ISSUE TITLE
YouPHPTube empty pages after install on CentOS

### ISSUE THREAD

**Issue by bgmeet** [DanielnetoDotCom/YouPHPTube#799]
Hello,
i did install YouPHPTube on my CentIS, http://video.lexpoker.tv/

For instalation i did use YouPHPTube-master exctract to my server dir and install with browser. Fill every step all green but no admin panel. :(

but as you can see noting show up, Download and install from Github.
Log in as admin but no admin panel at all
https://gyazo.com/bf1a8d881f132adf1222573485c0a161

Is there something i can do ?

It`s great product btw, just i dont know how to fix this.

Please if you have time to replay will be great.

Thank you in advanced.

Kind Regards:

**Comment by bgmeet** [comment]
Hello 
noting of this works. https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

[root@vpscfpw7 tube]# sudo git fetch --all && sudo git reset --hard origin/maste                                  r
fatal: Not a git repository (or any of the parent directories): .git
[root@vpscfpw7 tube]#
[root@vpscfpw7 tube]# git --version
git version 1.7.1
[root@vpscfpw7 tube]#

I did again replace all files from YouPHPTube-master in to install dir and i delete that log you ask for.
Its same as before. Noting is changed.

I hope for help again.

Kind Regards

**Comment by bgmeet** [comment]
There is no help for other distros only for Ubuntu...
Also devels can gave a hand if they can and have time of course.

Kind regards

**Comment by hersche** [comment]
UPDATE users SET user = 'admin', password = '53ba9f718a130de148e8107344509340', email = 'gushtericata@gmail.com', name = '', isAdmin = 1,canStream = false,canUpload = false,
    canViewChart = , status = 'a', photoURL = '', backgroundURL = '', recoverPass = '', about = '',  channelName = '5b32bb0bd04b7', emailVerified = false , analyticsCode = '' , modified = now() WHERE id = 1

i still find this in your log.

a failure is here: canViewChart = ,

but like said, i have fixed this yesterday. i can also show you which commits made that. maybe clone again, if nothing else works.

> [root@vpscfpw7 tube]# sudo git fetch --all && sudo git reset --hard origin/maste r

do simply a **git pull** in your youphptube-root.

> There is no help for other distros only for Ubuntu...

sorry, but we can't handle every system, webserver etc.. we have a tutorial about Debian 9.3 as well, but this is from a user, i cannot install that also just for try.

if you like to write a tutorial for centos, that's welcome and i would love to put it into the wiki. i would refer to your name/website/blog/this issue in the wiki. but don't except i can test that.

> Also devels can gave a hand if they can and have time of course.

i also devel on that ;)

if i find another bug, i will try to fix it as fast as i can, but since i see the old bug in the log.. i'm not shure if the update really worked.

it seems related to this, but the user does not seem to reopen it and closed it by itself.. maybe fixed?
https://github.com/DanielnetoDotCom/YouPHPTube/issues/797

**Comment by bgmeet** [comment]
[root@vpscfpw7 tube]# git pull
fatal: Not a git repository (or any of the parent directories): .git
[root@vpscfpw7 tube]#
Same story.
Also files from YouPHPTube-master are last version right ? 
No idea what to do right now. Will wait if you have solution.

Thanks for the help tho :) I do apretiate it :)

Kind regards

**Comment by hersche** [comment]
yes, there you are right.

can it be that you have downloaded the zip-file? then, git pull is not possible and you have to download the zip-file again from master..

you can also do a 

    git clone https://github.com/DanielnetoDotCom/YouPHPTube.git

this will create a subfolder YouPHPTube. if you enter the YouPHPTube-folder, you can do a git pull there.

you also can rename or copy the files, in case of copy, you have to get shure the hidden folder **.git** is copied too.

**Comment by bgmeet** [comment]
[root@vpscfpw7 tube]# git pull
Already up-to-date.

Hey now everything work :)
Now i see admin panel :)
Thank you! thank you !
I hope will have no problem istalling encoder and stream and other stuff :)

Thank you again !
Kind Regards:

**Comment by hersche** [comment]
perfect! :)

so also the other issue is solved for shure..;)

this was a very fresh bug, i am not working much on the encoder at the moment, but i think you will have a good expirience there :)

i close it then.. 

have fun ;)

**Comment by bgmeet** [comment]
Yeah everything work for now.. Tomorrow will try install stream.
Its late now.
Again thank you for your help :)

Kind Regards:
