### ISSUE TITLE
Bucket Policy

### ISSUE THREAD

**Issue by zoxee** [DanielnetoDotCom/YouPHPTube#826]
Lieber Hersche, hast post :)

**Comment by zoxee** [comment]
Dear Daniel, Dear Hersche,

I stumbled on another problem. I have this morning set up a policy for my video bucket,
so people are unable to download encoded videos.

- .Bucket Policy was sent to Hersche by email. -
![snap34](https://user-images.githubusercontent.com/25471117/42283488-ecdd0612-7fa9-11e8-9e8b-0bc4117ff736.jpg)

I did not have to change the encryption of the bucket, it was already set at AES-256.

The end result is that previously encoded videos that were already in the bucket, no matter if they
were pulled from youtube or were uploaded directly from my computer, are played properly and cause an access denied when trying to download them using a Chrome plugin like FlashDownloader.

So everything works perfectly.

The only problem is that any video that is encoded after this policy change, appears in the video manager with a playing time of EE: EE: EE. Thumbnails are generated correctly, but playing fails.

Are there changes in the settings of the AWS plugin that need to be made so that the encoded
videos get played ? I really lost on this one, I would be glad if you guys could provide me with a
solution to resolve this.

Thanks in advance,
Dan

**Comment by zoxee** [comment]
Should i maybe attach the same policy of the bucket to the user's policy ?
Or maybe reissue new credentials with a new user ?

**Comment by zoxee** [comment]
Found this in S3 help section, maybe it will tell you something ?

"After you enable default encryption for a bucket, the following encryption behavior applies:

There is no change to the encryption of the objects that existed in the bucket before default encryption was enabled.

When you upload objects after enabling default encryption:

If your PUT request headers don't include encryption information, Amazon S3 uses the bucket’s default encryption settings to encrypt the objects.

If your PUT request headers include encryption information, Amazon S3 uses the encryption information from the PUT request to encrypt objects before storing them in Amazon S3. If the PUT succeeds, the response is an HTTP/1.1 200 OK with the encryption information in the response headers. For more information, see PUT Object."

**Comment by zoxee** [comment]
After setting up the policy, i get this return message from s3 when trying to download a previously encoded video from the video manager (although this fmovie just plays fine inside YPT)

![snap35](https://user-images.githubusercontent.com/25471117/42287480-cc05ef50-7fb6-11e8-8e13-a0dba2fa64ac.jpg)

This all tells me it is an encryption issue. Hopefully you will tell me more :/

Cheers...

**Comment by zoxee** [comment]
Hey Guys, please help ;(

**Comment by hersche** [comment]
hey, we reconized your message. aws s3 is a topic i personaly never touched, daniel can say more to this.

we discussed a bit on this (we are both quite busy) and we are not shure if it's possible to protect completly against such browser-addons.

the point is: a such plugin can use the same identifiers as the browser (also same referrer etc). 
at some point, the browser need to be able to download the video for playing it. if the browser can download it, why shouldn't be that possible for a plugin with good access to the browser-functions?

i guess (like said, i never used aws) you tried to restrict it to the refferer ("aws:Referer": [ in mailed config), but like said, that can be the same as usual on a plugin.

daniel was say, it would make sense to check it for non-browsers, i agree it can help.

but to make it clear: i can set every of those parameters with the default webdeveloper-tools in firefox. it is not really protect-able by this.

my recommandation, but thats hard to implement and i am not shure how and if this ever works with YPT, would be DRM.

with DRM, users can still download it, but the mediafile can expire. after expire, you cannot view it. but also there: make a screenvideo and you have it withouth DRM. but by direct download, it's at least non-sense to upload it somewhere else and maybe it won't work on desktop also (it need keys).

from netflix i know, current firefox-versions (since 50.0 or so) have native DRM-support under linux (windows and mac got it earlier i think)

**Comment by zoxee** [comment]
I understand, will take a look at DRM and see what can be done.
Thanks for the help anyways, i'm pretty busy myself :+1: 

Cheers to both,
Dan

**Comment by DanielnetoDotCom** [comment]
hi @zoxee 
"blur effect "
If you disable it you will see a very low quality image. the blur effect is to make the page a little nicer while the images are loading

ie that the one image lowquality https://demo.youphptube.com/videos/_YPTuniqid_5ad69c5b452dc3.75651755_thumbsSmallV2.jpg

and that is the image that are displayed after load https://demo.youphptube.com/videos/_YPTuniqid_5ad69c5b452dc3.75651755_thumbsV2.jpg

about the encryption ...

you got the images, because the images were extracted while it was being encoded 

I am not sure how the S3 decryption will work, but all documentations I saw, the decryption must be made on client side. and when you use the S3 you stream the video direct from the bucket, I could not find a way to request a "Presigned Request" and automatic decrypt it on amazon.

**Comment by zoxee** [comment]
Hi Daniel my brother, thanks for coming by.

Yeah i know about the image problem, in fact i know your whole script by heart now :)
I love your work, it is simply a masterpiece, a spine on which to build on is a breeze.
Back to the images, do you use some php graphic class somewhere to create those
bluring images ? if yes, if i deactivate it then maybe only normal thumbs will be created directly
instead of the blurry ones ?

What the encryption goes, i wrote my own php class and now any video uploaded to amazon
gets blocked with the same result you achieved by restricting access to videos uploaded directly
to the dedicated server when the AWS plugin is inactive. Just tested the 5 most famous
downloader plugins, not one managed to access any video, so problem solved i guess :)

Anyways, thanks for helping bro :)
Dan

**Comment by DanielnetoDotCom** [comment]
Hi @zoxee 

that css is what make the images blur

https://github.com/DanielnetoDotCom/YouPHPTube/blob/7f8a9be1285e1da133bc3e9dfa96b30b4c6cf9d3/view/css/main.css#L691

About the encryption, are you saying you are able to block the browser tools to form download your videos?
can you please share more details?

Are you able to block this one?
https://www.internetdownloadmanager.com/

**Comment by hersche** [comment]
> add the chanadd the channel thumbnail in the navbar so the person logged in
knows he is logged in :)

we thinked about that (in fact, i began doing this once), came to the conclusion to make the navbar flexible with plugins and it ended in upgrade to bootstrap 4 for the moment.. and there' s some stuff to do ;)

**Comment by zoxee** [comment]
Yes Daniel. Also IDM. Any Plugin in fact. MP4 & MP3 are completely out of reach for any downloader.
Here are two examples: The first ist the podcast platform i coded, the second is from YPT.

![snap41](https://user-images.githubusercontent.com/25471117/42299796-6e306232-800d-11e8-99ea-f12105fe0fc6.jpg)
![snap45](https://user-images.githubusercontent.com/25471117/42299804-81e8c1e8-800d-11e8-966b-419b689ac69e.jpg)

Unfortunately, i can not share more details at this point, because i am about to launch something big this week by which this very special protection will allowing my users to fully protect and monetize their content. It is so to speak one of the key commercial advantages of my system, so i can not give it away.

And i can not miss this launch under any circumstances. My last wife behaved like a hurricane, meaning she came to me wet and soft and when she left after 13 years, she took my child, my car, my house and my dog... i really need to get back on my feet now. But if you are interested and my operation goes well over the 3-4 next months, i am open for a cooperation with you guys, like adding my code to your hosted solutions, offering thereby your clients a tremendous commercial argument.

Hope you understand.
Cheers.
Dan

**Comment by DanielnetoDotCom** [comment]
That is great.

I really sorry about your wife.

and your contribution will be very welcome. and count on us to help you, we will do our best.

I hope one day we can reproduce your feature.
