### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by deaf-tv** [DanielnetoDotCom/YouPHPTube#878]
Database Problem 

{"error":"Error performing query 'ALTER TABLE `users` ADD COLUMN `analyticsCode` VARCHAR(45) NULL DEFAULT NULL ;\n': Duplicate column name 'analyticsCode'

"}

Updated
Version 5,5 to 5.6

**Comment by DanielnetoDotCom** [comment]
Looks like you skiped an update, try to change (roll back) the version on your configuration table on your Streamer database

and update again, do not skip any update

**Comment by deaf-tv** [comment]
![updated](https://user-images.githubusercontent.com/17132516/42941812-36db80a8-8b5e-11e8-9b12-acf113669fe1.jpg)

![no view1](https://user-images.githubusercontent.com/17132516/42941823-3fdf8dde-8b5e-11e8-9da7-4d823b7a95d8.jpg)


- Database Tabelle: configurations Version  5.6 to 5.5
- Theme to default
- Stream off

Updated 5.5 to 5.6
no View

**Comment by DanielnetoDotCom** [comment]
can you please check the log file to see why it is blank?

**Comment by deaf-tv** [comment]
E-Mail sent

log

**Comment by DanielnetoDotCom** [comment]
Next time, please paste your log file here.

In your log file i found this:

[sqlDAL::writeSql] Prepare failed: (1054) Unknown column 'externalOptions' 

this is for version 5.8 and as you told me your version is 5.6, check if you dont have more updates on the update menu.

**Comment by deaf-tv** [comment]
Database  Version 5.6 to 5.5

Update  5.5 to 5.7
Database  5.7 to 5.5

Update 5.5 to 5.8

Homepage View good

**Comment by DanielnetoDotCom** [comment]
You not suppose to make 

Update 5.5 to 5.7 or Update 5.5 to 5.8

It should be 5.5 -> 5.6 then  5.6 -> 5.7 and then  5.7 -> 5.8

**Comment by ehk20** [comment]
Seeing similar problem here. Coming from a pre-5 version database updates, done in strict order using /update/?done=1 stops working after applying 5.6 database update. Since I saw a an error for missing column 'externalOptions'. I updated the scheme manually from the differences I could find in the current versions and from the subsequent errors it seems this field only gets added in v5.8 update! For the record I added the fields after 5.6 as follows:
```
ALTER TABLE `users` 
ADD  `canViewChart` TINYINT(1) NOT NULL DEFAULT 0,
ADD  `externalOptions` TEXT NULL,
ADD  `first_name` VARCHAR(255) NULL DEFAULT NULL,
ADD  `last_name` VARCHAR(255) NULL DEFAULT NULL,
ADD  `address` VARCHAR(255) NULL DEFAULT NULL,
ADD  `zip_code` VARCHAR(45) NULL DEFAULT NULL,
ADD  `country` VARCHAR(100) NULL DEFAULT NULL,
ADD  `region` VARCHAR(100) NULL DEFAULT NULL,
ADD  `city` VARCHAR(100) NULL DEFAULT NULL
```
and then ran the remaining updates to the latest version with some errors on the user table along the way since the fields already existed
