### ISSUE TITLE
What are the Limitations of the free YouPHPTube

### ISSUE THREAD

**Issue by honeyfairy** [DanielnetoDotCom/YouPHPTube#892]
Does Youphptube have any limitations to the amount and length of videos that can be stored and served?

I am a bit confused as I have seen users saying they are limited to 120 and 184mins. And asking about the FULL PACK.
Please clarify, is there a commercial version of Youphptube?

Also, are there speed limitations on the buffering of the free version? 
Some users were speaking about slow buffering issues. Please clarify

**Comment by DanielnetoDotCom** [comment]
There are no limitations.

All limitations are hardware limitations.

There is a script calculation..., your maximum file size can be only 50% of your RAM memory because the script needs to copy files between locations and handles it on the virtual memory.

In Example, if you want to upload a 4GB file you will need to have at least 8 GB Ram on the server otherwise you will have a Memory Leaks - Allowed memory size of # bytes exhausted error.
