### ISSUE TITLE
Manual authentication of uploaders

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#938]
I have a spammer...

keeps uploading hundred of videos in the middle of the night.

can I force a manual approval to upload videos?

**Comment by DanielnetoDotCom** [comment]
We dont have that option now

**Comment by timmayy** [comment]
is there a way to have uploads disabled by default on new accounts then?

**Comment by DanielnetoDotCom** [comment]
Here 

![image](https://user-images.githubusercontent.com/18009293/43740659-3b79c384-99a2-11e8-81c6-d55e3bf2b0cd.png)

**Comment by CorpCaleCloud** [comment]
can't you just delete his account? 
also you set the configuration advance in the plugin section so that only verified emails can login so even if they attempt to create and account unless you authorise it they cannot login and if the do you can delete the account so double security. also create yourself a word or excel doc with a list of banned users so you don't get confused later on if you have two many user trying to spam you.

As long as they have to create and account and be verified you have control if they abuse the system with deletion of account

![unverifed](https://user-images.githubusercontent.com/25417743/44040633-b08f4100-9f13-11e8-849b-a3947974f5c8.PNG)
